### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by AtomicGaming666** [FarisCode511/BlackRAT#1]
hey this is no problem with the RAT its for the BlackNET

i got it all working i just cant get it to work out side of my PC so i want to put it on my other PCs so i can control them and stuff 

but it just not working 

Hit me up on discord if you know how to fix @ AtomicGaming666#8864

**Comment by Vedant-Bhalgama** [comment]
Hey Atomic!

You need to enable port forwarding on your router if you want to send the backdoor outside the the network

**Comment by FarisCode511** [comment]
@AtomicGaming666 
Where did you install it locally or on a hosting

**Comment by AtomicGaming666** [comment]
On my local

**Comment by Vedant-Bhalgama** [comment]
Then it will be inside the network only.

**Comment by AtomicGaming666** [comment]
I have it port forward and stuff but will only work on my pc what’s a good free host I can use

**Comment by AtomicGaming666** [comment]
Wait what port it use

**Comment by FarisCode511** [comment]
@AtomicGaming666 you don't need any port you need a hosting use 000webhost for free if you have on local you can't use it outside your PC until you forward port 80👍🏻

**Comment by AtomicGaming666** [comment]
hey o know its closed and all but im using 000webhost and i have put all my files in but i cant get it working
i just get this 
![image](https://user-images.githubusercontent.com/39306849/88502816-054b5300-d013-11ea-9445-2fb1e63164f3.png)

**Comment by FarisCode511** [comment]
@AtomicGaming666 

1. Upload your files inside public_html folder
2. Remove index.html not index.php
3. Grant 775 permissions to every file and folder
